# Generated by Django 5.0.3 on 2024-10-30 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_userprofile_location_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics/'),
        ),
        migrations.CreateModel(
            name='CarForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('accidental_background', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='cars_for_sale/')),
                ('leftside_img', models.ImageField(blank=True, null=True, upload_to='cars_for_sale/')),
                ('rightside_img', models.ImageField(blank=True, null=True, upload_to='cars_for_sale/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='cars_for_sale/')),
                ('registration_number', models.CharField(max_length=100)),
                ('insurance_end_date', models.DateField()),
                ('ownership_type', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.oiltype')),
            ],
        ),
        migrations.CreateModel(
            name='CarForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rent_car_image', models.ImageField(blank=True, null=True, upload_to='cars_for_rent/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.oiltype')),
            ],
        ),
    ]
