# Generated by Django 5.0.3 on 2024-10-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_brand_oiltype_alter_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carforrent',
            name='rent_car_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cars_for_rent/'),
        ),
        migrations.AlterField(
            model_name='carforsale',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cars_for_sale/'),
        ),
        migrations.AlterField(
            model_name='carforsale',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cars_for_sale/'),
        ),
        migrations.AlterField(
            model_name='carforsale',
            name='leftside_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/cars_for_sale/'),
        ),
        migrations.AlterField(
            model_name='carforsale',
            name='rightside_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/cars_for_sale/'),
        ),
    ]
