# Generated by Django 5.0.3 on 2024-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_carforrent_rent_car_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
