# Generated by Django 5.0.3 on 2024-11-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
