# Generated by Django 5.0.3 on 2024-11-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_car_is_for_rent_car_is_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='carforrent',
            name='is_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carforrent',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carforsale',
            name='is_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carforsale',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
