# Generated by Django 5.0.3 on 2024-11-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_carforrent_owner_alter_carforsale_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carforrent',
            name='is_for_rent',
            field=models.BooleanField(default=True),
        ),
    ]
